dma-contiguous: rename reserved to linux,cma
Variscite uses the cma kernel parameter to adjust the cma size
according to the amount of memory installed on each SoM.

When the cma heap size is specified on the kernel command line instead
of DT, the heap gets named 'reserved' instead. This breaks NXP
gstreamer plugins that are hardcoded to 'linux,cma'.

When the cma parameter is used, the linux,cma device tree node is bypassed:
https://github.com/Freescale/linux-fslc/blob/5.15-2.0.x-imx/kernel/dma/contiguous.c#L409-L413

And the cma name "reserved" is used instead of "linux,cma":
https://github.com/Freescale/linux-fslc/blob/5.15-2.0.x-imx/kernel/dma/contiguous.c#L233-L234

Unfortunately, NXP gstreamer plugins, imx-vpu-hantro, imx-vpu-hantro-vc,
etc. are hardcoded to use /dev/dma_heap/linux,cma:

Examples:
https://source.codeaurora.org/external/imx/gst-plugins-base/tree/gst-libs/gst/allocators/gstdmabufheaps.c?h=lf-5.15.32-2.0.0#n96
./gstreamer1.0-plugins-base/1.18.5.imx-r0/git/gst-libs/gst/allocators/gstdmabufheaps.c:96:  fd = open ("/dev/dma_heap/linux,cma", O_RDWR);
./isp-imx/4.2.2.16.0-r0/isp-imx-4.2.2.16.0/appshell/display/WlDisplay.cpp:480:        pdisplay->cma_fd = open_cma("/dev/dma_heap/linux,cma");
./imx-vpu-hantro/1.25.0-r0/imx-vpu-hantro-1.25.0/h1_encoder/software/linux_reference/ewl/ewl_x280_common.h:65:#define MEMALLOC_MODULE_PATH        "/dev/dma_heap/linux,cma-uncached"
./imx-vpu-hantro/1.25.0-r0/imx-vpu-hantro-1.25.0/decoder_sw/software/linux/dwl/dwl_linux.h:72:#define MEMALLOC_MODULE_PATH "/dev/dma_heap/linux,cma-uncached"
./imx-test/1_7.0+AUTOINC+b364c1aacc-r0/git/test/mxc_v4l2_vpu_test/pitcher/dmabuf.c:442: return dma_heap_alloc_dma_buf("/dev/dma_heap/linux,cma", size);
./imx-test/1_7.0+AUTOINC+b364c1aacc-r0/git/test/mxc_v4l2_vpu_test/pitcher/dmabuf.c:447: return dma_heap_alloc_dma_buf("/dev/dma_heap/linux,cma-uncached", size);
./imx-test/1_7.0+AUTOINC+b364c1aacc-r0/git/test/bat/bat-devicetree.sh:74:    */clocks/*|*/base/clock-*|*/ccm@*|*/scg*@*|*/interrupt-controller@*|*/gpc@*|*linux,cma|*/cpus/l2-cache*)
./imx-vpu-hantro-vc/1.7.0-r0/imx-vpu-hantro-vc-1.7.0/usr/include/hantro_VC8000E_enc/ewl_x280_common.h:44:#define MEMALLOC_MODULE_PATH        "/dev/dma_heap/linux,cma-uncached"
etc...

As a result, these plugins do not work when using the cma parameter,
and produce errors like below:

  # GST_DEBUG="3" XDG_RUNTIME_DIR="/run/user/0" gst-launch-1.0 filesrc location=/home/root/BigBuckBunny.mp4 typefind=true ! video/quicktime !    aiurdemux ! queue max-size-time=0 ! vpudec ! waylandsink

  Setting pipeline to PAUSED ...
  ====== VPUDEC: 4.6.4 build on Jan 18 2022 09:10:37. ======
          wrapper: 3.0.0 (VPUWRAPPER_ARM64_LINUX Build on Jul 16 2021 02:05:07)
          vpulib: 1.1.1
          firmware: 1.1.1.43690
  0:00:00.159802804  1209 0xaaaae0df2980 ERROR                default gstallocatorphymem.c:150:base_alloc: Allocate phymem 16777232 fail.

  0:00:00.159838929  1209 0xaaaae0df2980 ERROR                default gstvpu.c:90:gst_vpu_allocate_internal_mem: Could not allocate memor
  0:00:00.159908305  1209 0xaaaae0df2980 ERROR         vpu_dec_object gstvpudecobject.c:342:gst_vpu_dec_object_start:<vpudecobject0> gstl
  0:00:00.159937555  1209 0xaaaae0df2980 WARN            videodecoder gstvideodecoder.c:2682:gst_video_decoder_change_state:<vpudec0> err
  ERROR: from element /GstPipeline:pipeline0/GstVpuDec:vpudec0: Could not initialize supporting library.
  Additional debug info:
  ../git/gst-libs/gst/video/gstvideodecoder.c(2682): gst_video_decoder_change_state (): /GstPipeline:pipeline0/GstVpuDec:vpudec0:
  Failed to start decoder
  ERROR: pipeline doesn't want to preroll.
  Failed to set pipeline to PAUSED.
  Setting pipeline to NULL ...
  Freeing pipeline ...

For now, rename 'reserved' to 'linux,cma' until a better option
is available.

In the future, these plugins should be modified
to both '/dev/dma_heap/linux,cma*' or '/dev/dma_heap/reserved*'
like the following example:
https://git.libcamera.org/libcamera/libcamera.git/tree/src/libcamera/pipeline/raspberrypi/dma_heaps.cpp

Signed-off-by: Nate Drude <nate.d@variscite.com>